#!/bin/bash

upchk_dir=/var/lib/apt-upchk
workroot=${upchk_dir}/workroot

exec apt-get --allow-unauthenticated \
  -o Dir=${workroot} \
  -o Dir::State::status=${workroot}/var/lib/dpkg/status \
  "$@"
