#!/bin/bash

test -r /etc/apt-upchk/notify.conf && . /etc/apt-upchk/notify.conf
: ${mailto:=root}
: ${mode=master}

upchk="`/usr/share/apt-upchk/scripts/upchk`"

if [ "$mode" == "master" ]; then
  upchk=$(echo "$upchk" | /usr/share/apt-upchk/scripts/genreport)
  test -z "$upchk" && exit 0
else
  (echo "upchk" | egrep -q "(<updatepkg>|<keptbackpkg>)") || exit 0
fi

echo "Subject: [`hostname -s`] Updated Package Available
X-Sender: apt-upchk-notify (`hostname -s`)
Content-Type: text/plain; charset=us-ascii
To: `echo "${mailto}" | sed -e 's/^  *//; s/  *$//; s/  */, /g'`

$upchk
" | /usr/sbin/sendmail $mailto
