#!/bin/bash

scriptdir=/usr/share/apt-upchk/scripts
test -r /etc/apt-upchk/notify.conf && . /etc/apt-upchk/notify.conf
: ${mailto:=root}
: ${mode=single}

upchkout="`${scriptdir}/upchk`"
test "$?" == "0" && exit 0

if [ "$mode" != "multi" ]; then
  upchkout=$(echo "$upchkout" | ${scriptdir}/report)
  test "$?" == "0" && exit 0
fi

echo "Subject: [`hostname -s`] Updated Package Available
X-Sender: apt-upchk-notify (`hostname -s`)
Content-Type: text/plain; charset=us-ascii
To: `echo "${mailto}" | sed -e 's/^  *//; s/  *$//; s/  */, /g'`

$upchkout
" | /usr/sbin/sendmail $mailto
