#!/usr/bin/perl
# -*- cperl -*-
package main;
use lib "/usr/share/apt-upchk/lib";
use AptUpchk::Report::SingleHost;

if (__FILE__ eq $0) {
    use strict;
    use warnings;
    use XML::DOM;

    our %opt = (config => @ARGV && $ARGV[0] || "/etc/apt-upchk/report.conf",
		"ignore-name" => [],
		"ignore-type" => []);
    if ( -r $opt{config} ) {
	do $opt{config};
	die "Error in config file: $@\n" if $@;
    }

    my $exitcode = 0;
    my $dom = XML::DOM::Parser->new->parse(*STDIN);
    my $rep = AptUpchk::Report::SingleHost->new(doc => $dom,
						"ignore-type"=>$opt{"ignore-type"},
					        "ignore-name"=>$opt{"ignore-name"},
					       );

    $rep->report and $exitcode = 100;

    exit($exitcode);
}

1;
