#!/usr/bin/perl
# -*- cperl -*-
package main;
use lib "/usr/share/apt-upchk/lib";

if (__FILE__ eq $0) {
    use strict;
    use warnings;
    use XML::DOM;
    my $report_class = "AptUpchk::Report::SingleHost";

    if ($ARGV[0] && ($ARGV[0] eq "-m" || $ARGV[0] eq "--mail")) {
	$report_class =  "AptUpchk::Report::Mail"
    }
    eval "use $report_class";

    our %opt = (config => @ARGV && $ARGV[0] || "/etc/apt-upchk/report.conf",
		"exclude-byname" => [],
		);
    if ( -r $opt{config} ) {
	do $opt{config};
	die "Error in config file: $@\n" if $@;
    }

    my $exitcode = 0;
    my $dom = XML::DOM::Parser->new->parse(*STDIN);
    my $rep = $report_class->new(doc => $dom,
			        "exclude-byname"=>$opt{"exclude-byname"},
			       );

    $rep->report and $exitcode = 100;

    exit($exitcode);
}

1;
