#!/usr/bin/perl
# -*- cperl -*-
package main;
use strict;
use warnings;
use Cwd;
use lib "/usr/share/apt-upchk/lib";
use AptUpchk::Notify::Daemon;

if (__FILE__ eq $0) {
    if (@ARGV && $ARGV[0] eq "-d"){
	print "start daemon...\n";
	AptUpchk::Notify::Daemon->new(debug => 1)->run;
    }
    elsif (fork) {
	exit(0);
    } else {
	close(STDIN);
	close(STDOUT);
	close(STDERR);
	chdir("/");
	AptUpchk::Notify::Daemon->new->run;
    }
}
