#!/usr/bin/perl
package main;
use strict;
use warnings;
use lib "/usr/share/apt-upchk/lib";
use AptUpchk::Notify::Client;

# turn around XML::XQL bug....
$ENV{TERM}="dumb";

if (__FILE__ eq $0) {
    use IO::File;
    my $infh = IO::File->new("-");
    my $report = "";
    my $header = 1;
    while ( <$infh> ) {
	/^<\?xml/ and $header = 0;
	next if $header;
	$report .= $_;
    }
    AptUpchk::Notify::Client->new(daemon => "/usr/share/apt-upchk/scripts/summary-sender")->senddoc($report);
    exit(0);
}
